file_object = open('testFile.txt')
data = file_object.readline()
file_object.close()
file_object = open('testFile.txt')
data2 = file_object.read(50)
data3 = file_object.readlines()
data4 = list(file_object)
data5 = tuple(file_object)
file_object.close()
print(data)
print(data2)
print(data3)
print(data4)
print(data5)